# Traduções português -> alemão
usuario = Benutzername
senha = Passwort
acessar = Anmeldung
cadastrar = Registrieren
usuario-encontrado = 404: Benutzer nicht gefunden
usuario-existente = 403: Benutzer bereits vorhanden
usuario-adicionado = 201: Benutzer hinzugefügt.
motor = Motor
tipo-do-motor = Motortyp
tipo = Typ
em-linha = Reihe
boxer = boxer
V = V
quantidade-cilindros = Zyl-Anz
cilindradas = Hubraum
aspiração = Ansaugung
aspirado-naturalmente = Natürlich
turbo-compressor = Turbolader
super-compressor = Kompressor
combustivel = Kraftstoff
gasolina = Benzin
diesel = Diesel
material = Material
ferro-fundido = Gusseisen
liga-de-aluminio = Aluminiumlegierung
liga-de-titanio = Titanlegierung
tração = Antrieb
traseira = Heckantrieb
dianteira = Vorderradantrieb
integral = Allradantrieb
freios = Bremsen
popular = Standard
esportivo = Sport
corrida = Rennen
ceramica = Keramik
rodas = Räder
off-road = Offroad
chassi = Fahrgestell
suv = Geländewagen
sedan = Limousine
sport = Sportwagen
hatchback = Schrägheck
coupe = Coupé
suspensão = Federung
rally = Rallye
pintura = Lackierung
vermelho = Rot
amarelo = Gelb
azul = Blau
preto = Schwarz
nome = Name
dar-nome = Fahrzeug benennen
excluir = Löschen
novo = Neu
garagem = Garage
menu = Menü
sair = Ausfahrt
retornar = Zurück
carro = Auto
estatisticas = Daten
custo = Kosten
consumo = Verbrauch
peso = Gewicht
velocidade-maxima = Hchtchwindgkt
aceleração = Bschlng
torque = Drehmoment
potencia = Leistung
manuseio = Handling
frenagem = Bremsen
quer-excluir-carro = Möchten Sie das ausgewählte Fahrzeug löschen?
confirmar = Bestätigen