# Traduções português -> inglês
usuario = Username
senha = Password
acessar = Login
cadastrar = Sign Up
usuario-encontrado = 404: User not found
usuario-existente = 403: User already exists
usuario-adicionado = 201: User added. Logging in...
motor = Engine
tipo-do-motor = Engine type
tipo = Type
em-linha = Inline
boxer = boxer
V = V
quantidade-cilindros = Cyl Amt
cilindradas = Cylinders
aspiração = Aspiration
aspirado-naturalmente = Natural
turbo-compressor = Turbocharger
super-compressor = Supercharger
combustivel = Fuel
gasolina = Gas
diesel = Diesel
material = Material
ferro-fundido = Cast iron
liga-de-aluminio = Aluminum alloy
liga-de-titanio = Titanium alloy
tração = Traction
traseira = Rear
dianteira = Front
integral = All-wheel
freios = Brakes
popular = Standard
esportivo = Sport
corrida = Race
ceramica = Ceramic
rodas = Wheels
off-road = Off-road
chassi = Chassis
suv = Suv
sedan = Sedan
sport = Sports
hatchback = Hatchback
coupe = Coupe
suspensão = Suspension
rally = Rally
pintura = Paint
vermelho = Red
amarelo = Yellow
azul = Blue
preto = Black
nome = Name
dar-nome = Name car
excluir = Delete
novo = New
garagem = Garage
menu = Menu
sair = Exit
retornar = Return
carro = Car
estatisticas = Stats
custo = Cost
consumo = Consumption
peso = Weight
velocidade-maxima = Top speed
aceleração = Acceleration
torque = Torque
potencia = Power
manuseio = Handling
frenagem = Braking
quer-excluir-carro = Do you want to delete the selected car?
confirmar = Confirm
