# Traduções português -> espanhol
usuario = Usuario
senha = Contraseña
acessar = Iniciar sesión
cadastrar = Registrarse
usuario-encontrado = 404: Usuario no encontrado
usuario-existente = 403: Usuario ya existente
usuario-adicionado = 201: Usuario añadido. Iniciando sesión...
motor = Motor
tipo-do-motor = Tipo de motor
tipo = Tipo
em-linha = En línea
boxer = boxer
V = V
quantidade-cilindros = Cant Cil
cilindradas = Cilindrada
aspiração = Aspiración
aspirado-naturalmente = Natural
turbo-compressor = Turbo
super-compressor = Supercargador
combustivel = Combustible
gasolina = Gasolina
diesel = Diésel
material = Material
ferro-fundido = Hierro fundido
liga-de-aluminio = Aluminio
liga-de-titanio = Titanio
tração = Tracción
traseira = Trasera
dianteira = Delantera
integral = Total
freios = Frenos
popular = Estándar
esportivo = Deportivo
corrida = Carrera
ceramica = Cerámica
rodas = Ruedas
off-road = Todo terreno
chassi = Chasis 
suv = Suv
sedan = Sedán
sport = Deportivo
hatchback = Hatchback
coupe = Cupé
suspensão = Suspensión
rally = Rally
pintura = Pintura
vermelho = Rojo
amarelo = Amarillo
azul = Azul
preto = Negro
nome = Nombre
dar-nome = Nombrar vehículo
excluir = Eliminar
novo = Nuevo
garagem = Garaje
menu = Menú
sair = Salir
retornar = volver
carro = Auto
estatisticas = Stats
custo = Costo
consumo = Consumo
peso = Peso
velocidade-maxima = Veloc. maxima
aceleração = Aceleración
torque = Par motor
potencia = Potencia
manuseio = Manejo
frenagem = Frenado
quer-excluir-carro = ¿Desea eliminar el vehículo seleccionado?
confirmar = Confirmar