# Traduções português -> italiano
usuario = Nome utente
senha = Password
acessar = Accedi
cadastrar = Registrati
usuario-encontrado = 404: Utente non trovato
usuario-existente = 403: Utente già esistente
usuario-adicionado = 201: Utente aggiunto. Accesso in corso...
motor = Motore
tipo-do-motor = Tipo di motore
tipo = Tipo
em-linha = In linea
boxer = boxer
V = V
quantidade-cilindros = N. cilindri
cilindradas = Cilindrata
aspiração = Aspirazione
aspirado-naturalmente = Naturale
turbo-compressor = Turbo
super-compressor = Compressore
combustivel = Carburante
gasolina = Benzina
diesel = Diesel
material = Materiale
ferro-fundido = Ghisa
liga-de-aluminio = Lega di alluminio
liga-de-titanio = Lega di titanio
tração = Trazione
traseira = Posteriore
dianteira = Anteriore
integral = Integrale
freios = Freni
popular = Standard
esportivo = Sportivo
corrida = Corsa
ceramica = Ceramica
rodas = Ruote
off-road = Fuoristrada
chassi = Telaio
suv = Suv
sedan = Berlina
sport = Sportiva
hatchback = Hatchback
coupe = Coupé
suspensão = Sospensione
rally = Rally
pintura = Vernice
vermelho = Rosso
amarelo = Giallo
azul = Blu
preto = Nero
nome = Nome
dar-nome = Assegna nome
excluir = Elimina
novo = Nuovo
garagem = Garage
menu = Menu
sair = Esci
retornar = Torna
carro = Auto
estatisticas = Dati
custo = Costo
consumo = Consumo
peso = Peso
velocidade-maxima = Veloc. massima
aceleração = Accelerazione
torque = Coppia
potencia = Potenza
manuseio = Gestione
frenagem = Frenata
quer-excluir-carro = Vuoi eliminare l'auto selezionata?
confirmar = Conferma