# Traduções português
usuario = Usuário
senha = Senha
acessar = Acessar
cadastrar = Cadastrar
usuario-encontrado = 404: Usuário não encontrado
usuario-existente = 403: Usuário já existe
usuario-adicionado = 201: Usuário adicionado. Entrando...
motor = Motor
tipo-do-motor = Tipo de motor
tipo = Tipo
em-linha = Em linha
boxer = boxer
V = V
quantidade-cilindros = Qnt Cil
cilindradas = Cilindradas
aspiração = Aspiração
aspirado-naturalmente = Natural
turbo-compressor = Turbo compressor
super-compressor = Super compressor
combustivel = Combustível
gasolina = Gasolina
diesel = Diesel
material = Material
ferro-fundido = Ferro fundido
liga-de-aluminio = Liga de alumínio
liga-de-titanio = Liga de titânio
tração = Tração
traseira = Traseira
dianteira = Dianteira
integral = Integral
freios = Freios
popular = Popular
esportivo = Sport
corrida = Corrida
ceramica = Cerâmica
rodas = Rodas
off-road = Off-Road
chassi = Chassi
suv = SUV
sedan = Sedan
sport = Esportivo
hatchback = Hatchback
coupe = Coupé
suspensão = Suspensão
rally = Rally
pintura = Pintura
vermelho = Vermelho
amarelo = Amarelo
azul = Azul
preto = Preto
nome = Nome
dar-nome = Dar nome
excluir = Excluir
novo = Novo
garagem = Garagem
menu = Menu
sair = Sair
retornar = Voltar
carro = Carro
estatisticas = Stats
custo = Custo
consumo = Consumo
peso = Peso
velocidade-maxima = Veloc. Máx
aceleração = Aceleração
torque = Torque
potencia = Potência
manuseio = Manuseio
frenagem = Frenagem
quer-excluir-carro = Deseja excluir o carro selecionado?
confirmar = Confirmar
